/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:fd7b99b7-23db-412e-87ba-b755ecf20941",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_bThIAXc2j",
    "aws_user_pools_web_client_id": "3omdrkqr6aj7upt8gd5kdff4m8",
    "oauth": {}
};


export default awsmobile;
